### ISSUE TITLE
Better 404 page

### ISSUE THREAD

**Issue by mattwynne** [cucumber-attic/website#19]

**Comment by romaingweb** [comment]
First attempt: https://www.cukes.info/404
I moved the error handling to the dynamic app in d863697.

**Comment by aslakhellesoy** [comment]
Awesome! Looks like we need to set up the `www` subdomain.

**Comment by mattwynne** [comment]
I've fiddled around in CloudFlare and I think https://www.cukes.info is now working, though I seem to have problems with my local DNS. Can someone else test please?

**Comment by jbpros** [comment]
It redirects to https://cukes.info here. Looks all good to me. Thanks @mattwynne!

**Comment by mattwynne** [comment]
I say this is good enough for now, thanks @romaingweb!
