### ISSUE TITLE
Add a public slack channel

### ISSUE THREAD

**Issue by tooky** [cucumber-attic/website#22]
I wonder if a public slack channel might be easier and less intimidating for some users looking for help than IRC?

https://github.com/rauchg/slackin/blob/master/Readme.md

**Comment by mattwynne** [comment]
:+1:

**Comment by aslakhellesoy** [comment]
I like the idea, but worried about fragmentation. Long term we should only have a single chat channel.

Can you use slack without signing up?

**Comment by mattwynne** [comment]
I agree @aslakhellesoy, I'd suggest this replacing IRC. What I like is that:
- slack has avatars, and I think that makes it feel more friendly
- we can integrate it in a browser so we can host it on cukes.info

If I'm honest, then also:
- I'm in slack every day personally, so it would make it more convenient for me.

**Comment by aslakhellesoy** [comment]
I'm reluctant to add a chat channel that requires someone to sign up for yet another social network like Slack.

**Comment by aslakhellesoy** [comment]
I suggest we host our private [Shout IRC](http://shout-irc.com/) server on irc.cukes.info and theme the UI a little so we can embed it on our pages.

**Comment by mattwynne** [comment]
I think I have the same feeling Aslak - especially since Slack is a commercial enterprise, it feels a bit wrong pushing people to use them in order to chat with us. However, from a UX point of view, wouldn't it be much the same? People will still have to "sign up" for an IRC account won't they?

**Comment by tooky** [comment]
@aslakhellesoy I agree that requiring signup might be an issue, but it might be an interesting experiment? The irc channel doesn't get that much love lately, I wonder if a better channel would create for better conversations?

**Comment by Kosmas** [comment]
Sorry for coming late to the party. For what is worth, personally I haven't used irc for quite a few years. But have been using slack quite a bit.

**Comment by aslakhellesoy** [comment]
You don't have to sign up for an IRC account, no. You just pick a nickname and off you go. People won't even notice it's IRC unless they have used IRC before. It looks like any old chat.

I think the reason the IRC channel is quiet is because of bad UI.

**Comment by mattwynne** [comment]
@tooky is this dealt with by https://gitter.im/cucumber/chat? Can we close this?

**Comment by tooky** [comment]
Yep this achieves the same goal!
