### ISSUE TITLE
Normal font hard to read

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/website#24]
I find the normal font (Lato, 16px) very hard to read. The "i"s and "l"s are frequently antialiased to the point where they are just a grey line. 

![screen shot 2015-04-05 at 09 33 12](https://cloud.githubusercontent.com/assets/1000/6996284/d814db9a-db76-11e4-9d20-3b1b88c679de.png)

Look at the different "i"s.

It seems improve a little if we change text colour from the branded black `#1B1D1E` to `#000000` and increase the font size to 18px, but it's still not great. We're currently using font weight 300. Should we increase to 400?

**Comment by jbpros** [comment]
+1 

I find the text size too small anyway, regardless of rendering issues. I had the feeling we had it larger a few weeks ago but it might be my brain playing tricks :)

Your suggestion of 18px font size and #000 color makes it good enough, imo.

Also, we're currently loading the 300 and 700 weights from Google for Lato. 400 is the `normal` weight but as it is not loaded, it leads to inconsistent rendering between browsers. On my MBA, Chrome seems to display normal-weight text at 300 while Safari seems to use my local Lato font and display the 400 weight. I suggest we dump 700, make 300 the default weight and use 400 as bold (or dump 300, use 400 as default and 700 as bold, but I find it gross :p)
