### ISSUE TITLE
Left nav links too low contrast when clicked

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/website#26]
Light green on gray :-/

![screen shot 2015-04-05 at 20 20 23](https://cloud.githubusercontent.com/assets/1000/6998260/3fff4014-dbd2-11e4-8ea2-e23613553f87.png)

**Comment by romaingweb** [comment]
This looks like it was fixed.  The gray is very light now (nearly white). @aslakhellesoy, can you confirm this?

**Comment by aslakhellesoy** [comment]
It was probably fixed a long time ago, but since the less recompilation was broken it didn't show up online.
