### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by mattwynne** [cucumber-attic/website#30]
Kinds of events:
- CukeUp conferences (Sydney, London, NYC, Bangalore...)
- Conference speaking engagements
- Community meetups
- Public trainings
- Maybe webinars etc.

Acceptance criteria:
- easy to add new events, even if you're not very technical
- nice URLs
- RSS feed of events
- attributes of an event:
  - date / time
  - location
  - list of who's involved
  - URL
  - image
  - brief description / abstract
  - title

Nice to have:
- publish to Lanyrd and similar sites

**Comment by mattwynne** [comment]
After pairing on this today with @aslakhellesoy in the events branch, we've decided we'd like to use [this Lanyrd guide](http://lanyrd.com/guides/cucumber-events/) as our database, and pull in events from their feed. We'll render the event listing on our site from that, but if we've built our own page (it must have a template name that matches the Lanyrd page) then we'll link to that from our index.

That way the community can easily add new events from Lanyrd, and they'll automatically appear on the Cucumber site.

**Comment by aslakhellesoy** [comment]
Some more ideas:

## Meetup.com

While I agree we (Cucumber team) should try to use Lanyrd as our main database, I think we should also pull in events from other calendars, such as the BDDLondon meetup group. There's a few around the world:
- http://www.meetup.com/VancouverBDD/
- http://www.meetup.com/Brisbane-Software-Testers-Meetup/
- http://www.meetup.com/West-Malling-Kent-Software-Tester-Automation-Agile-Group/

And many more... Some of these groups won't have BDD or Cucumber as a topic for every meeting, so we should filter out irrelevant meetings.

Meetup organisers can send us a pull request to add their meetup iCal feed. Then we'll scan that feed and include all events that have either "BDD" or "Cucumber" in their `name` (using the [REST API](http://www.meetup.com/meetup_api/docs/2/events/)) 

## Conference talks are only in pages

I have also thought about Conference speaking engagements. Take Matt's workshop at Agile 2015  for example. I'm not sure it makes sense to add that to Lanyrd. It would make more sense to simply add a markdown page for that, with the event details in the front matter.

So what we display on the /events page will be the union of our filtered iCal feeds and our custom pages.

## World map

iCal events can have a `GEO` field with lat/lon, and both Lanyrd and Meetup.com populate those fields. We can also add geo locations to the frontmatter for conf talks.

So our /events page could display both a calendar and a map.

**Comment by mattwynne** [comment]
First pass shipped in 7aa1b0ec37d4755dbfa2b3bb82d1e18e420ee336

**Comment by mattwynne** [comment]
Also, we decided that it _would_ make sense to add conference talks to Lanyard.

**Comment by mattwynne** [comment]
Having seen the nitty-gritty details of the Lanyrd iCal feed (e.g. timezone issues, no pubDate / mtime) I'm thinking we'd be safer to maintain our own 'database' of events in yaml. It's not ideal as the feed won't automatically update, but I think it safer: we can make sure we keep a history of past events, for example, and we can control the quality of the data.

Maybe we could have rake tasks for manually importing from the feeds into the yaml?

**Comment by mattwynne** [comment]
@jbpros @romaingweb we've shipped a first iteration of this, and I think now it could do with some design love. Some ideas:
- Tiles / cards rather than just a list of events.
- A event listing sidebar widget we can use on other parts of the site (e.g. the blog / homepage)
- Separate tabs for upcoming / past events
- Better looking individual event pages (e.g. https://cukes.info/events/cukeup-australia-2015)

**Comment by mattwynne** [comment]
I'll close this ticket, and we can put new iterations in separate tickets.
