### ISSUE TITLE
Update install cucumber link

### ISSUE THREAD

**Issue by mlvandijk** [cucumber-attic/website#314]
On main page, from button "Install Cucumber" link directly to https://docs.cucumber.io/installation/ instead of https://docs.cucumber.io

**Comment by JohJohan** [comment]
I will pick up this issue!

**Comment by JohJohan** [comment]
@mlvandijk Where can i find the button to edit? When i search the button i cannot find it in the project?

**Comment by mlvandijk** [comment]
@JohJohan I'm not sure; I don't use work on this project a lot. Maybe @mattwynne can help you?

**Comment by mattwynne** [comment]
Ah. that page is now on Squarespace, so only a few of us have permissions to manage it at the moment.

I can change the button to link to "/installation" if that's what we want. Do we think that's the most useful entry-point for first timers?

**Comment by mlvandijk** [comment]
Well, it is if we want to point them to how to install? Alternatively we cpuld point them to the 10 min tutorial.
 If we want to point them to the docs in general I'd rename the button maybe?

**Comment by mattwynne** [comment]
My thinking with that link was that whatever the main CTA on the Cucumber homepage was for someone who wants the open source, should take them to the docs homepage, and the docs homepage should take it from there.

I think we said before that we'd like to reword the docs homepage a bit didn't we?

Let me try renaming the button and let's see how that feels.

**Comment by mattwynne** [comment]
OK. I've changed the main CTA to "Automate with Cucumber" and it still links to the docs homepage.

Can anyone think of a better verb that still clearly differentiates what you do with Cucumber vs what you do with Cucumber Pro or a training course?!

In the "below the fold" heading about Cucumber ("Automate") I've added two buttons - *Get Started* which links to the /guides page (from where you can find the 10-minute tutorial... or would it be better to link straight to that?!) and then *Learn More* which links to the docs homepage.

WDYT?

**Comment by mlvandijk** [comment]
LGTM!
