### ISSUE TITLE
[Website][Bug] Enterprise Support packages link returns a 404 resulting in the default not found slim

### ISSUE THREAD

**Issue by amp4045** [cucumber-attic/website#318]
From the https://cucumber.io/support#slack page, the "Enterprise section" provides a link to the CucumberPaidSupportPlan.pdf. Currently when clicking that link (https://cucumber.io/CucumberPaidSupportPlans.pdf) leads to a 404 and the default not found slim.

It appears the functionality occurs on line 89 within https://github.com/cucumber/website/blob/master/apps/dynamic/views/support.slim with the appropriate PDF to be displayed at https://github.com/cucumber/website/blob/master/apps/static/public/CucumberPaidSupportPlans.pdf. 

I attempted to work on a PR for this... but i'm not very familiar with web dev, nor could I see where the pdfs/assets were being pushed out. 

This error was also reproduced standing up the site locally (in the dev environment). See attachment.
![cucumbersupportpdferror](https://user-images.githubusercontent.com/15094255/47835718-bc9e3180-dd7b-11e8-910d-0b3f6e354318.png)

![cucumbersupportpdfresults](https://user-images.githubusercontent.com/15094255/47835746-db9cc380-dd7b-11e8-9033-9bca551e451c.png)

**Comment by aslakhellesoy** [comment]
@mattwynne could you have a look at this please? I suppose it happened as part of the recent website changes. Either restore the doc, remove the link or update it.

**Comment by mattwynne** [comment]
Thanks for reporting @Downright-Development. I've moved the support page over to the new squarespace site.

**Comment by aslakhellesoy** [comment]
Thanks @mattwynne. Minor niggle - Enterprise Support now links to Premium Support. Could you make that consistent please?
