### ISSUE TITLE
Anchors are broken

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/website#34]
Try this: https://cukes.info/docs/reference#command-line

The fix in b8f54653b5cb8d2ffbfd2f6d328ffd7b1b77f1f3 makes the header visible, but it breaks the left nav, which is no longer aligned with the visible header.

I think the solution for this is CSS, not JavaScript. Something like this: http://fellowtuts.com/html-css/offsetting-anchor-hash-tag-links-to-adjust-for-fixed-header/

/cc @romaingweb

**Comment by romaingweb** [comment]
Indeed, I don't know how I missed this.  I'm going to revert the changes and try to fix it with CSS.

**Comment by romaingweb** [comment]
3b1e9dd javascript was the way to go.  Can you test it again?

**Comment by aslakhellesoy** [comment]
@romaingweb Did you mean "css was the way to go"?

It's still broken. Try this:
- Go to https://cucumber.io/docs/reference/browser-automation#multiple-browsers
- Click on the "Multiple Browsers" link in the left nav

It jumps back again underneath the header.

**Comment by romaingweb** [comment]
Ok I see, it's definitely an issue... but a bit more complex.  It "only" jumps when the hash of an anchor is already present in the url.  I'll see how I can tweak the JS to prevent that behaviour.

**Comment by aslakhellesoy** [comment]
How was the initial fix implemented? Are there any other relevant commits than b8f5465 and 3b1e9dd? Together they don't seem to change anything.

Wouldn't it be better to avoid JavaScript for this completely? Can't this be fixed with CSS alone? That would definitely be my preference.
