### ISSUE TITLE
Handling 500 errors

### ISSUE THREAD

**Issue by mattwynne** [cucumber-attic/website#37]
If I look at https://cukes.info/events/cukeup-australia-2015 right now it's showing a 500 error page, but I have no way of knowing what's going on.

To do:
- [x] Rollbar on 500 error so we get notified
- [x] Better looking page

**Comment by romaingweb** [comment]
Errors are now reported on Rollbar. I also fixed the one you mentioned.

**Comment by mattwynne** [comment]
Thanks @romaingweb! What does the page look like now? Can we close this?

**Comment by romaingweb** [comment]
Just put some custom design for the 500 error page.
