### ISSUE TITLE
Better feedback when a template fails to render

### ISSUE THREAD

**Issue by mattwynne** [cucumber-attic/website#41]
I just had a hiccup where added Theo's first blog post, and got [a weird error](https://circleci.com/gh/cucumber/website/334) that turned out to be due to him not being in the authors list in the config.

It would have helped a great deal if the backtrace had pointed me to the actual line of the `feed.xml` template, instead of mistakenly pointing me to some random line in `page.rb`.

**Comment by aslakhellesoy** [comment]
We could also move the parts of the website that non-technical people are likely to edit frequently to something friendlier, like WordPress.
