### ISSUE TITLE
Cannot read Parts of your website

### ISSUE THREAD

**Issue by thinkrapido** [cucumber-attic/website#5]
Please refactor your css.

![image](https://cloud.githubusercontent.com/assets/1568087/5975804/f3efa76a-a885-11e4-9ac2-3d12143a7b3b.jpg)

**Comment by jbpros** [comment]
Thanks for reporting this, @thinkrapido. Can you explain a bit more about the issue? Is that a screenshot of the page right after loading, with the header almost completely hidden or is it scrolled a bit? Or is the problem related to the Cucumber school ribbon?

**Comment by thinkrapido** [comment]
Sorry for being not verbose enough.

The left side of the page is cut. That's all.
The given screenshot is from my iPad.
It is the main page.

**Comment by romaingweb** [comment]
The site is more responsive overall, this should not be a problem anymore.

**Comment by thinkrapido** [comment]
cool, I'll visit it in near future
