### ISSUE TITLE
Document CLI options

### ISSUE THREAD

**Issue by dandv** [cucumber-attic/website#55]
Some other tools pass-through CLI options to cucumber, and had to fish them out from the code:

https://chimp.readme.io/docs/command-line-options#section-cucumber-options-

**Comment by aslakhellesoy** [comment]
I skimmed that link, and it seems you're talking about cucumber.js. I agree we should add it to the web site, but have you this?

```
cucumber.js --help
```

**Comment by romaingweb** [comment]
Closed due to inactivity
