### ISSUE TITLE
Migrate wiki

### ISSUE THREAD

**Issue by romaingweb** [cucumber-attic/website#64]
Process:
1. Pick existing Wiki page
2. Manually migrate all content to the website, using the sitemap to figure out where to put it
3. Don't just copy/paste. Review and rewrite if needed
4. Remove content of the Wiki page with links to the new location

Pages to migrate from https://github.com/cucumber/cucumber/wiki:
- [ ] Home
- [ ] A Table Of Content
- [ ] A Whole New World
- [ ] Autotest Integration
- [ ] Background
- [ ] Browsers and Transactions
- [ ] Calling Steps from Step Definitions
- [ ] Conjunction Steps (Antipattern)
- [ ] Console Colours
- [ ] Continuous Integration
- [ ] Contributing
- [ ] Cucumber Backgrounder
- [ ] Cucumber Feature
- [ ] Cucumber for Perl
- [ ] Cucumber JVM
- [ ] cucumber.yml
- [ ] Custom Formatters
- [ ] Debugging
- [ ] Environment Variables
- [ ] Examples
- [ ] Feature Coupled Step Definitions (Antipattern)
- [ ] Feature Introduction
- [ ] Fixtures
- [ ] FunFX and Flex
- [ ] Get in touch
- [ ] Gherkin
- [ ] Given When Then
- [ ] Given when then (new)
- [ ] Hooks
- [ ] Install
- [ ] Introduction to Cucumber for non programmers
- [ ] IronRuby and .NET
- [ ] IronRuby and Mono
- [ ] Javascript and AJAX
- [ ] Jenkins integration
- [ ] JRuby and Java
- [ ] Merb
- [ ] Mocking and Stubbing with Cucumber
- [ ] Multiline Step Arguments
- [ ] Patterns
- [ ] PHP
- [ ] Profiles
- [ ] Projects Using Cucumber
- [ ] Python
- [ ] RDoc
- [ ] Related tools
- [ ] RSpec Expectations
- [ ] Ruby on Rails
- [ ] Running Features
- [ ] SAP Enterprise Portal Behavior Testing
- [ ] Scenario Outlines
- [ ] Setting up Selenium
- [ ] Setting up Steam
- [ ] Sinatra
- [ ] Snailgun and Cucumber
- [ ] Spoken languages
- [ ] Step Argument Transforms
- [ ] Step Definitions
- [ ] Step Organisation
- [ ] subdomain_fu and incorrect redirection to " body You are being redirected body " page
- [ ] Tables
- [ ] Tags
- [ ] Troubleshooting
- [ ] Tutorials and Related Blog Posts
- [ ] Upgrading
- [ ] Using AE
- [ ] Using MiniTest
- [ ] Using Rake
- [ ] Using RCov with Cucumber and Rails
- [ ] Using Test::Unit
- [ ] Watircraft
- [ ] watircuke
- [ ] Wire Protocol

**Comment by mlvandijk** [comment]
I'd be happy to help, but it's my understanding that the intended target for all documentation is now: https://github.com/cucumber/docs.cucumber.io

**Comment by mattwynne** [comment]
Thanks @mlvandijk that's correct. If you're interested in helping out, ping @plaindocs as he's best placed to tell you where he needs help the most.

**Comment by mlvandijk** [comment]
@mattwynne Thanks! Will do :)
