### ISSUE TITLE
Use own calendar for events

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/website#70]
Lanyrd has been down for 2 weeks, and Meetup.com is flaky. We need our own calendar for events.
- [ ] Web UI for managing events
- [ ] Store everything in our own database
- [ ] Batch job for scraping events from external ical sources (lanyrd, meetup.com etc)

**Comment by mattwynne** [comment]
Instead of a Web UI, what about using a Google Calendar? That’s pretty reliable and would save the hassle of building infrastructure.

Totally agree about the batch job though.

**Comment by mattwynne** [comment]
We may address this tech debt as part of #71

**Comment by theo-england** [comment]
Doesn't feel like a priority on the website right now - there's a bunch of things that seem more important on the website. 

We got unlucky with it crashing a few times, but I think in general it's OK.
