### ISSUE TITLE
Add public training landing page (Nov London, with George)

### ISSUE THREAD

**Issue by theo-england** [cucumber-attic/website#73]
- [ ] Display the training on the homepage (existing one)
- [ ] Add a custom event on the events index
- [ ] Add table/calendar on the training index
- [ ] Design the page (https://docs.google.com/document/d/1RJGoGtrbcs-34BOcQbd-3ydvYRKMjfIzINQVbBVA7N0/edit#heading=h.e8uhlupycc3l)

**Comment by mattwynne** [comment]
See if you can do this yourself, or book some pairing time with @aslakhellesoy for this. Use the same process as you do for a blog post PR, but create a new 'event' page in https://github.com/cucumber/website/tree/master/apps/dynamic/views/events - you can plagiarise the frontmatter from the `cukeup-australia-2015.slim` page, but use an `.md` extension instead and write the content like a blog post.
