### ISSUE TITLE
Add brand guidelines page

### ISSUE THREAD

**Issue by jbpros** [cucumber-attic/website#74]
The current brand guidelines live in https://github.com/cucumber-ltd/brand as a [PDF](https://github.com/cucumber-ltd/brand/blob/master/Cucumber_Brand_V1.0.pdf).

We'd like to deprecate that PDF in favour of an HTML version of it, easily reachable on the website ([cucumber.io/brand](https://cucumber.io/brand)?).
- [ ] Import content from the PDF into an HTML page
- [ ] Review all guidelines for obsolete information, don't forget to:
  - [ ] Review colours
  - [ ] Fix font guidelines https://github.com/cucumber-ltd/brand/issues/3

**Comment by mattwynne** [comment]
I'm closing this as I don't want it hanging round in the backlog, and it feels like Romain has more important things to do. That said, I don't mind if you want to re-open this and JFDI :)
