### ISSUE TITLE
Create sponsor section

### ISSUE THREAD

**Issue by theo-england** [cucumber-attic/website#79]
Hello - I need to include a sponsor area on the CukeUp! page. The section needs to accommodate each sponsor's logo. Each logo will need to be clickable to their website.  

I've put all the logos on dropbox here - https://www.dropbox.com/sh/ymgiv9eosgnbnpq/AAD74sIjoeeWppuFPOZoicLVa?dl=0

Organisers - Cucumber (https://cucumber.io/) and Magentys (http://magentys.io/)
Gold sponsors - Suncorp (http://www.suncorp.com.au/) OpenBet (https://www.openbet.com/) and Elabor8 (http://elabor8.com.au/). 
Bronze sponsors ustwo (https://ustwo.com/) and Thoughtworks (https://www.thoughtworks.com/)

**Comment by romaingweb** [comment]
I'm going to take care of that today...  I forgot all about it, sorry.  Is it ok to replace the section: "DO YOU WANT TO SPONSOR?" with these?

**Comment by mattwynne** [comment]
Yes, that’s fine. We’re only 2 days away now and unlikely to get new sponsors!

cheers,

Matt

—

matt@cucumber.io

m: +44(0)7974 430184

**Comment by romaingweb** [comment]
Fixed in 374c1880502480d18ba859d521e94d9acc8b22a4.
