### ISSUE TITLE
Alternative Feature Directory

### ISSUE THREAD

**Issue by kpughmisc** [cucumber-attic/website#81]
I like to look at acceptance testing from the customer’s point of view.  One issue that has been brought up a few times is that cucumber tests tend to be kept in the developer’s environment and so they are not easily available/viewable by the customer/tester.   

The wiki version of Fit (FitNesse) overcomes this by having all tests in a wiki which is searchable.  Tests are executed from within that environment and the results easily seeable.   But some have technical issues with the environment in which FitNesse executes its tests. 

What I propose is something a cross between these two and somewhat how some current requirement/test tools work.   And there may already be something in the works on this.  if that's the cases, please send me a link to it. 

Tests (e.g. feature files) would be kept in a separate requirements directory hierarchy, which may or may not parallel the source code hierarchy.    Non-developers would be able to view and possibly alter these tests (under revision control).   

At test time, the feature files would be either individually, as a group, or as a composition be submitted to cucumber.   The program could examine the files for tags (ala how cucumber currently works). and create one of more feature files based on the requested tags   The program would keep track of the source path of the feature files submitted.   As cucumber produces results, the output would be placed back into a parallel directory structure. For example, the html result of 

customertests/login/mylogin.feature 
would be put into 
customertestresults/login/mylogin.html 

Appropriate links could be added so that results are accessible via the hierarchy structure (to keep everything linked in a browser).   The non-developer would be able to browse the results to see current status of tests that have be run.

**Comment by mattwynne** [comment]
Hi, have you looked at www.relishapp.com?

Also https://cucumber.pro is coming...
