### ISSUE TITLE
Change training destination page on events page (from Lanyrd to our page)

### ISSUE THREAD

**Issue by theo-england** [cucumber-attic/website#86]
Hello!

On https://cucumber.io/events, I want to change the destination when I click on the Perth course. 

Currently it goes to - http://lanyrd.com/2015/bdd-kickstart-perth/

I want it to go to - https://cucumber.io/events/bdd-kickstart-perth-2015

**Comment by mattwynne** [comment]
I think you need to change the frontmatter on the bdd-kickstart-perth-2015.md page to make sure the ical_url matches the lanyrd page. Did you try that?

**Comment by romaingweb** [comment]
This seems to work now. I'm closing the issue.
